if: branch = master

env:
  global:
    - DOCKER_REPO=bxggs
    - DOCKER_IMAGE=travis-dockerhub-test
    - DEFAULT_DOCKER_TAG=latest

services:
  - docker

before_script:
  - docker build -t "$DOCKER_REPO/$DOCKER_IMAGE:$DEFAULT_DOCKER_TAG" .

deploy:
  provider: script
  script: bash -c 'echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push "$DOCKER_REPO/$DOCKER_IMAGE:$DEFAULT_DOCKER_TAG"'
